Updates.
wowvv0w/djmax-random-selector-v pull request #4
Opened 2022-02-26 17:20 UTC by quiettbee

신규 업데이트

* 설치된 DLC 감지 추가

2022-02-27 05:42 UTC, wowvv0w requested changes
코멘트를 확인해주십시오.

DLC 감지 기능은 상상도 못했던 방식이었습니다. 이 기능 덕분에 사용하기 더 편리해질 것 같습니다. 감사합니다.

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/ViewModels/MainViewModel.cs
> +using DjmaxRandomSelectorV.Views;
이 프로젝트는 MVVM 패턴을 최대한 고수하려 하고 있습니다. Binding을 사용해주시기 바랍니다.
```suggestion
```

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/ViewModels/MainViewModel.cs
> +                            window.WindowState = WindowState.Minimized;
`Topmost`가 항상 `True`로 되어있어 불편함이 있습니다. 이 코드에 `Topmost` 값을 변경하는 코드를 넣는 것을 제안합니다.

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/ViewModels/SettingViewModel.cs
> +        private int updated;
좀 더 직관적인 변수명을 사용하면 좋을 것 같습니다.
```suggestion
private int dlcCount;
```

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
배경색을 `DockPanel.Background`로 옮긴 이유는 무엇입니까? `Window.Background`에 그대로 놔둬도 작동에 문제는 없었습니다.

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/Views/SettingView.xaml
> +                <RowDefinition Height="11*"/>
이 Row를 추가한 이유가 무엇입니까?

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/Views/SettingView.xaml
> +                                Style="{StaticResource SettingDetectButton}"/>
이런 유틸리티 기능을 하는 버튼은 `SettingWindowButton` 스타일을 사용합니다. `SettingWindowButton`을 사용해주십시오.

2022-02-27 05:42 UTC, wowvv0w commented on DjmaxRandomSelectorV/ViewModels/SettingViewModel.cs
> +            bool dlccontained = true;
Boolean 명명규칙 적용
```suggestion
bool isContained = true;
```

2022-02-28 11:16 UTC, quiettbee commented on DjmaxRandomSelectorV/ViewModels/MainViewModel.cs
> +using DjmaxRandomSelectorV.Views;
문제점을 인지하였으며 Views를 임포트하여 사용한 AlwaysOnTop의 핫키 코드를 MVVM 패턴을 위반하지 않는 방향으로 수정하겠습니다.

2022-02-28 11:25 UTC, quiettbee commented on DjmaxRandomSelectorV/ViewModels/MainViewModel.cs
> +                            window.WindowState = WindowState.Minimized;
MVVM 패턴 위반 오류 수정과 함께 변경하겠습니다.

2022-03-02 16:41 UTC, wowvv0w commented
기능이 대거 추가됨에 따라 이 PR과 충돌이 다소 발생해, 두 커밋의 변경점을 유지한 채 해결하였습니다.

2022-03-15 09:07 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
전체화면 위에서 프로그램을 보이게 하기 위한 변경사항입니다.

2022-03-15 09:07 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/SettingView.xaml
> +                <RowDefinition Height="11*"/>
제거하였습니다.

2022-03-15 09:08 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/SettingView.xaml
> +                                Style="{StaticResource SettingDetectButton}"/>
버튼 크기가 커 디자인을 해칠 우려가 있어 개별 스타일을 사용하였습니다.

2022-03-15 10:16 UTC, wowvv0w commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
```Window.Background```로 다시 옮기고 ```AllowsTranparency = true```를 지우고 시도해도 똑같이 작동하는 것을 확인했습니다. 따라서 ```Window.Background```로 다시 옮기는 것을 제안합니다. 혹시 놓친 의도가 있다면 말씀해주세요.
그리고 전체화면이라 함은 디맥 디스플레이 설정을 의미하는 것인가요? 전체화면 앱 위에 보이게 하려면 오버레이밖에 방법이 없는 것으로 알고 있습니다. 실제로 제가 디스플레이 설정을 Full Screen으로 하고 시도했을 때는 Alt+Tab과 다를 바 없이 작동했습니다.

2022-03-15 10:39 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
AOT 기능은 Window Background가 투명일 때 정상적으로 동작합니다.
AOT 기능 추가와 함께 `Window.Background` 내 속성을 `Dockpanel.Background` 로 옮긴 것도 그 이유입니다.

제가 해당 기능을 시험하였을 때, Alt+Tab과 달리 디제이맥스 프로세스가 최소화 되지 않고 포커스만 풀렸고 랜덤선택기 프로세스가 최상단에 위치했습니다.
만약 변경된 MainView 사용 시에도 AOT 기능이 의도대로 동작하지 않고 디제이맥스 프로세스가 최소화된다면 알려주세요. 정상 동작하지 않는다면 삭제하겠습니다.

2022-03-15 11:36 UTC, wowvv0w commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
실험 결과입니다:

----

1. VS2022의 '실행' 버튼을 통해 실행한 경우
> 디맥 디스플레이 설정: Bordered Window

(F2기능)ON: 포커스 고정됨, 정상 작동
OFF: 포커스 고정됨, 정상 작동

> 디맥 디스플레이 설정: Full Screen

ON: 포커스가 고정되나 보이지 않음
*ON일 때 선곡기 창 크기만큼의 영역 위를 마우스 클릭하면 포커스가 풀리고 선곡기에 고정됨, 디맥 최소화됨
OFF: 포커스 고정됨, 정상 작동

----

2. exe를 직접 실행시킨 경우
> 디맥 디스플레이 설정: Bordered Window

ON: 포커스가 풀리고 선곡기에 고정됨, 디맥 최소화되지 않음
OFF: 포커스 고정됨, 정상 작동

> 디맥 디스플레이 설정: Full Screen

ON: 포커스가 풀리고 선곡기에 고정됨, 디맥 최소화됨, 
OFF: 다른 창이 최소화 되어 있지 않을 시 해당 창으로 포커스가 고정됨, 모두 최소화 되어 있을 시 포커스 고정됨

----

어디서 실행하는가에 따라 결과가 달라지는게 이상하지만 원인을 모르겠습니다. 위의 결과와 동일하게 나타납니까?

2022-03-16 08:24 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
해당 실험과 추가 실험을 진행하였습니다.

> DMRV 1.2.0 / Full Screen
정상 작동하지 않음

> DMRV 1.1.2 / Full Screen
이전에 정상작동함을 확인하였으나 현재 작동하지 않음

현재 해당 기능은 정상작동하지 않음을 확인하여 AOT 기능은 삭제하였습니다.

Commit `8b5c609` push 전 확인하였을 때 정상작동한 이유는 ALT+TAB 글리칭으로 인해 일시적으로 디제이맥스 프로세스가 보더리스 윈도우로 변경되어 작동한 것으로 보입니다.
또한 이전에 정상작동을 했던 것도 위와 관련이 있는것으로 보입니다.

2022-03-16 08:51 UTC, wowvv0w commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
Alt+Tab 글리치가 무엇인지와 DMRV 1.1.2 / 1.2.0이 무엇을 의미하는지에 대해 더 자세히 설명해주실 수 있으십니까? 디제이맥스의 버전은 v10xx를 쓰고 있는 것으로 알고 있습니다.

2022-03-16 09:09 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
해당 실험외에 추가 실험을 진행하였습니다.

> DMRV 1.2.0 / Full Screen
정상작동 X

> DMRV 1.1.2 / Full Screen
정상작동 X

현재 AOT 기능을 삭제하였습니다.
Commit [8b5c609](https://github.com/wowvv0w/djmax-random-selector-v/pull/4/commits/8b5c609083024ba6c5033e97508dc4f616e9a95b) 을 올리기 전에 한 실험에서 AOT 기능이 정상작동한 이유는 ALT+TAB 글리칭으로 인해 디제이맥스 프로세스가 보더리스 윈도우로 변경되어 정상작동한 것으로 보이며, 이전에 정상작동하였던 1.1.2 버전의 AOT가 작동하지 않는 이유는 다른 문제인것 같습니다.

2022-03-16 09:10 UTC, quiettbee commented on DjmaxRandomSelectorV/Views/MainView.xaml
> +        <SolidColorBrush Opacity="0" Color="White" />
해당 프로그램의 버전을 의미합니다. 1.1.2 베이스인 [5b5e829](https://github.com/wowvv0w/djmax-random-selector-v/pull/4/commits/5b5e829b45f41a4afb78a40260a0f6b7efeacff8) 버전과 1.2.0 베이스인 [8b5c609](https://github.com/wowvv0w/djmax-random-selector-v/pull/4/commits/8b5c609083024ba6c5033e97508dc4f616e9a95b)을 말합니다.

2022-03-16 10:22 UTC, wowvv0w approved these changes

2022-03-16 10:34 UTC, merged